version: '3.3'
services:
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'students'
        #database user for api
        MYSQL_USER: 'apiuser1'
        #api user password
        MYSQL_PASSWORD: 'password'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '6603:3306'
      expose:
        - '3306'
      network_mode: host        
        # Where our data will be persisted
      volumes:
        - my-db:/var/lib/mysql

    
    flask:
      build: ./flask
      container_name: flask-api
      restart: always
      environment:
        - APP_NAME=MyFirstAPI
      network_mode: host
      ports:
        - 5000:5000

volumes:
  my-db: